// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.3
// source: midpoint.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Midpoint_GetMidpoint_FullMethodName = "/grpc.Midpoint/GetMidpoint"
)

// MidpointClient is the client API for Midpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MidpointClient interface {
	GetMidpoint(ctx context.Context, in *MidpointRequest, opts ...grpc.CallOption) (*MidpointResponse, error)
}

type midpointClient struct {
	cc grpc.ClientConnInterface
}

func NewMidpointClient(cc grpc.ClientConnInterface) MidpointClient {
	return &midpointClient{cc}
}

func (c *midpointClient) GetMidpoint(ctx context.Context, in *MidpointRequest, opts ...grpc.CallOption) (*MidpointResponse, error) {
	out := new(MidpointResponse)
	err := c.cc.Invoke(ctx, Midpoint_GetMidpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MidpointServer is the server API for Midpoint service.
// All implementations must embed UnimplementedMidpointServer
// for forward compatibility
type MidpointServer interface {
	GetMidpoint(context.Context, *MidpointRequest) (*MidpointResponse, error)
	mustEmbedUnimplementedMidpointServer()
}

// UnimplementedMidpointServer must be embedded to have forward compatible implementations.
type UnimplementedMidpointServer struct {
}

func (UnimplementedMidpointServer) GetMidpoint(context.Context, *MidpointRequest) (*MidpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMidpoint not implemented")
}
func (UnimplementedMidpointServer) mustEmbedUnimplementedMidpointServer() {}

// UnsafeMidpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MidpointServer will
// result in compilation errors.
type UnsafeMidpointServer interface {
	mustEmbedUnimplementedMidpointServer()
}

func RegisterMidpointServer(s grpc.ServiceRegistrar, srv MidpointServer) {
	s.RegisterService(&Midpoint_ServiceDesc, srv)
}

func _Midpoint_GetMidpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MidpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MidpointServer).GetMidpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Midpoint_GetMidpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MidpointServer).GetMidpoint(ctx, req.(*MidpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Midpoint_ServiceDesc is the grpc.ServiceDesc for Midpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Midpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Midpoint",
	HandlerType: (*MidpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMidpoint",
			Handler:    _Midpoint_GetMidpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "midpoint.proto",
}
